// Set heuristics on / off
pub const FEATURE_NULL_MOVE_PRUNING: bool = true;
pub const FEATURE_TRANSPOSITION_TABLE: bool = true;
pub const FEATURE_PREORDER: bool = true;
pub const FEATURE_LMR: bool = false;
pub const FEATURE_KILLER_MOVE: bool = true;
pub const FEATURE_CAPTURE_HORIZON: bool = true;
pub const FEATURE_MAT_SOLVER: bool = false;
pub const FEATURE_CANNOT_WIN_FORCE_NULL: bool = true;
pub const FEATURE_ASPIRATION_WINDOW: bool = true;
